name: Bump children
on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to bump to'
        required: true
        default: '1.2.3'

jobs:
  bump:
    runs-on: ubuntu-latest
    ## Matrix task, repeats steps for each repo
    strategy:
      matrix:
        repo: ["cuddletech/child-one", "cuddletech/child-two"]
    steps:
      - uses: actions/checkout@v3
      - name: Repository Dispatch (Workflow Dispatch)
        uses: peter-evans/repository-dispatch@v2
        if: github.event_name == 'workflow_dispatch'
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: kick
          client-payload: '{"version": "${{ github.event.inputs.version }}"}'
      - name: Repository Dispatch (Release)
        uses: peter-evans/repository-dispatch@v2
        if: github.event_name == 'release'
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: kick
          client-payload: '{"version": "${{ github.event.release.tag_name }}"}'

