name: Bump children
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to bump to'
        required: true
        default: '1.2.3'

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: cuddletech/child-one
          event-type: kick
          client-payload: '{"version": "${{ github.event.inputs.version }}"}'


